name: Docker Publish
env: 
  DOCKER_BUILDKIT: 1
  
on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-publish.yml"
    branches:
      - main
    tags:
      - '*'

jobs:
  build_amd64:
    name: Build Docker image for amd64
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            langroid/langroid:latest-amd64
            langroid/langroid:${{ env.DOCKER_TAG }}-amd64
          build-args: |
              BUILDKIT_INLINE_CACHE=1            

  build_arm64:
    name: Build Docker image for arm64
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build and push arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            langroid/langroid:latest-arm64
            langroid/langroid:${{ env.DOCKER_TAG }}-arm64
          build-args: |
              TARGETARCH=arm64
              BUILDKIT_INLINE_CACHE=1            

  create_manifest:
    name: Create and push multi-arch manifest
    needs: [build_amd64, build_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Create and push latest manifest
        run: |
          # Remove existing manifest if it exists
          docker manifest rm langroid/langroid:latest || true
          
          # Create and push latest manifest
          docker manifest create langroid/langroid:latest \
            langroid/langroid:latest-amd64 \
            langroid/langroid:latest-arm64
          
          docker manifest push langroid/langroid:latest
