name: Doc pages

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs-deploy.yml"
    branches:
      - main
      - simpler_doc_linking

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install Poetry dependencies
        run: |
          poetry --version
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip
          
          poetry install --only docs --no-root --sync

      - name: Build MkDocs documentation
        # change this to -b gh-pages when ready to make docs public
        run: poetry run mkdocs gh-deploy -b gh-pages --force


#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          deploy_key: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: ./site
